name: my_website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "代码拉取"
        uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.X"

      - name: install dep
        run: npm install
      
      - name: build app
        run: npm run docs:build

      - name: copy file
        uses: appleboy/scp-action@master
        with:
          host: blog.zghtools.top
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          source: "dist/"
          target: "/text"
          strip_components: 1
          rm : true
          
    
    
    
